version: '3.8'

services:
  clubos-lite:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000